### ISSUE TITLE
xHE-AAC Support

### ISSUE THREAD

**Issue by eqfae** [qwerty12/mpv-winbuild#17]
https://github.com/qwerty12/mpv-winbuild/actions/runs/4074277609
It shows that it contains fdkaac
Unable to play this kind of audio

Find an available one.
https://github.com/MartinEesmaa/VVCEasy/blob/master/MPV.md

**Comment by qwerty12** [comment]
No, the mpv here uses fdk-aac's headers but it doesn't contain it proper - which is why I've never once made the claim that this supports xHE-AAC/listed that as a feature in the README. 

If you have libfdk-aac-2.dll (preferably built yourself using the mpv-winbuild-cmake from here), this mpv will use fdk-aac for decoding where appropriate if you set the `__MP_FDKAAC_PATH` environment variable to its path before starting mpv and the mpv property `ad` to `libfdk_aac`. Otherwise, it's probably best to use the builds you've listed.

**Comment by eqfae** [comment]
> No, the mpv here uses fdk-aac's headers but it doesn't contain it proper - which is why I've never once made the claim that this supports xHE-AAC/listed that as a feature in the README.
> 
> If you have libfdk-aac-2.dll (preferably built yourself using the mpv-winbuild-cmake from here), this mpv will use fdk-aac for decoding where appropriate if you set the `__MP_FDKAAC_PATH` environment variable to its path before starting mpv and the mpv property `ad` to `libfdk_aac`. Otherwise, it's probably best to use the builds you've listed.

```
mkdir build.ninja
mkdir /root/fdkaac
cd build.ninja/
export CC=/usr/bin/x86_64-w64-mingw32-gcc
export CXX=/usr/bin/x86_64-w64-mingw32-g++
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/root/fdkaac -G Ninja
cmake --build .
# [172/172] Creating library symlink libfdk-aac.so.2 libfdk-aac.so
cmake --install .
```
libfdk-aac-2.dll
I want to generate this dll file but I don't know how to do it

**Comment by qwerty12** [comment]
I have no idea how to cross-compile it outside of the confines of mpv-winbuild-cmake, to be honest. It's been a while since I've done this myself, but off the top of my head:

1. Clone https://github.com/qwerty12/mpv-winbuild-cmake somewhere
2. Set up your build environment: https://github.com/qwerty12/mpv-winbuild-cmake#setup-build-environment
3. Follow https://github.com/qwerty12/mpv-winbuild-cmake#building-software-first-time but stop where it says `ninja mpv`. Instead, run `ninja fdka` and libfdk-aac-2.dll will be somewhere in the build64 folder - somewhere

Building the toolchain does take a while if your system isn't fast; I have no idea if you can reuse your distro-provided MSYS etc. toolchain. Before you set aside the time needed for this, I don't think this really offers anything better than VVCEasy for your purposes

**Comment by eqfae** [comment]
Success Thank you
[libfdk-aac-2.zip](https://github.com/qwerty12/mpv-winbuild/files/10775640/libfdk-aac-2.zip)
